# Generated by Django 3.1.6 on 2021-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=50, verbose_name='Ссылка на фото')),
                ('full_text', models.TextField(verbose_name='Описание товара')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала акции')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания акции')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
    ]
