# Generated by Django 3.1.6 on 2021-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cena',
            field=models.CharField(default=1, max_length=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cena_action',
            field=models.CharField(default=123, max_length=10, verbose_name='Цена со скидкой'),
            preserve_default=False,
        ),
    ]
